name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.24'

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc g++

    - name: Build C
      run: |
        cd src/c
        gcc -O3 c_test.c -o ../../bin/c_test -pthread -lm

    - name: Build C++
      run: |
        cd src/cpp
        g++ -O3 -std=c++17 cpp_test.cpp -o ../../bin/cpp_test -pthread

    - name: Build Go
      run: |
        cd src/go
        go build -o ../../bin/go_benchmark go_benchmark.go

    - name: Build Rust
      run: |
        cd src/rust
        cargo build --release

    - name: Build Java
      run: |
        cd src/java
        javac -cp ../../json.jar JavaTest.java -d ../../bin

    - name: Create logs directory
      run: mkdir -p logs

    - name: Run Tests
      run: |
        echo "Running C tests..."
        ./bin/c_test 4
        
        echo "Running C++ tests..."
        ./bin/cpp_test 4
        
        echo "Running Go tests..."
        ./bin/go_benchmark 4
        
        echo "Running Java tests..."
        cd bin && java -cp .:../json.jar JavaTest 4 && cd ..
        
        echo "Running Python tests..."
        python src/python/python_test.py 4
        
        echo "Running Rust tests..."
        cd src/rust && cargo run --release -- 4

    - name: Process Results
      run: python process_logs.py

    - name: Upload Results
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-results
        path: |
          logs/
          benchmark_results.png