name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cpp-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install clang-format
      run: sudo apt-get install -y clang-format
    - name: Run clang-format
      run: find src/cpp -name '*.cpp' -o -name '*.h' | xargs clang-format -i --style=file

  python-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black
    - name: Run flake8
      run: flake8 src/python/ process_logs.py
    - name: Run black
      run: black --check src/python/ process_logs.py

  go-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.24'
    - name: Run gofmt
      run: |
        cd src/go
        test -z "$(gofmt -l .)"

  rust-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
    - name: Run rustfmt
      run: |
        cd src/rust
        cargo fmt -- --check
    - name: Run clippy
      run: |
        cd src/rust
        cargo clippy -- -D warnings