name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  c-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install clang-format
      run: sudo apt-get install -y clang-format
    - name: Run clang-format
      run: find src/c -name '*.c' -o -name '*.h' | xargs clang-format -i --style=file

  cpp-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install clang-format
      run: sudo apt-get install -y clang-format
    - name: Run clang-format
      run: find src/cpp -name '*.cpp' -o -name '*.h' | xargs clang-format -i --style=file

  python-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black pandas matplotlib numpy
    - name: Run flake8
      run: flake8 src/python/ process_logs.py
    - name: Run black
      run: black --check src/python/ process_logs.py

  java-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Download Checkstyle
      run: |
        curl -L -o checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.0/checkstyle-10.12.0-all.jar
    - name: Run checkstyle
      run: java -jar checkstyle.jar -c checkstyle.xml src/java/

  go-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Generate go.sum
      run: |
        cd src/go
        go mod tidy
    - name: Run gofmt
      run: |
        cd src/go
        test -z "$(gofmt -l .)"
    - name: Run go vet
      run: |
        cd src/go
        go vet ./...

  rust-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
        override: true
    - name: Run rustfmt
      run: |
        cd src/rust
        cargo fmt -- --check
    - name: Run clippy
      run: |
        cd src/rust
        cargo clippy -- -D warnings